name: build

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "51 3 * * 6" # Runs at 03:51, only on Saturday
jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos", "windows"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: Install dependencies
        run: shards install --without-development --release
      - name: Run tests
        run: |
          crystal build examples/lol.cr
          ./lol
          crystal spec
      - name: Build executable (macOS)
        if: matrix.os == 'macos'
        run: |
          brew update
          brew install libgc pcre2
          ln -s $(brew ls libgc | grep libgc.a) .
          ln -s $(brew ls pcre2 | grep libpcre2-8.a) .
          shards build --link-flags="-L $(pwd) $(pwd)/libgc.a $(pwd)/libpcre2-8.a" --release
          otool -L bin/lolcat
      - name: Build executable
        if: matrix.os != 'macos'
        run: shards build --release
      - name: Run executable (help)
        run: bin/lolcat --help
      - uses: actions/upload-artifact@v4
        with:
          name: lolcat-${{ matrix.os }}
          path: bin/${{ matrix.os == 'windows' && 'lolcat.exe' || 'lolcat' }}
